"""test after fix

Revision ID: c5618b3bdac0
Revises: 004554449425
Create Date: 2026-08-10 23:52:41.820568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5618b3bdac0'
down_revision: Union[str, Sequence[str], None] = '004554449425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_state_records', 'last_error',
               existing_type=sa.VARCHAR(length=500),
               comment='Safe error summary only — no stack traces or secrets.',
               existing_comment='Safe error summary only â€” no stack traces or secrets.',
               existing_nullable=True)
    op.alter_column('agent_state_records', 'safe_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Safe operational metadata — no customer data or secrets.',
               existing_comment='Safe operational metadata â€” no customer data or secrets.',
               existing_nullable=True)
    op.alter_column('notification_templates', 'variables',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('notification_templates', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'tenant-1'::character varying"))
    op.alter_column('notification_templates', 'agent_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'CommsAgent'::character varying"))
    op.alter_column('notification_templates', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('notification_templates', 'deleted_by',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_index('idx_managed_prompt_lookup', 'notification_templates', ['tenant_id', 'agent_type', 'channel', 'locale', 'type', 'is_active'], unique=False)
    op.create_index(op.f('ix_notification_templates_agent_type'), 'notification_templates', ['agent_type'], unique=False)
    op.create_index(op.f('ix_notification_templates_is_deleted'), 'notification_templates', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_notification_templates_tenant_id'), 'notification_templates', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_notification_templates_lookup', 'notification_templates', ['tenant_id', 'agent_type', 'channel', 'locale', 'type', 'version'])
    op.create_foreign_key(None, 'notification_templates', 'organizations', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.add_column('template_versions', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('template_versions', sa.Column('type', sa.String(length=50), nullable=True))
    op.add_column('template_versions', sa.Column('channel', sa.String(length=20), nullable=True))
    op.add_column('template_versions', sa.Column('locale', sa.String(length=10), nullable=True))
    op.add_column('template_versions', sa.Column('format', sa.String(length=20), nullable=True))
    op.add_column('template_versions', sa.Column('agent_type', sa.String(length=50), nullable=True))
    op.add_column('template_versions', sa.Column('variables', sa.JSON(), nullable=True))
    op.add_column('template_versions', sa.Column('template_is_active', sa.Boolean(), nullable=True))
    op.add_column('template_versions', sa.Column('restored_from_version', sa.Integer(), nullable=True))
    op.add_column('template_versions', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('template_versions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('template_versions', sa.Column('deleted_by', sa.String(length=100), nullable=True))
    op.create_index('idx_active_template_version', 'template_versions', ['template_id'], unique=True, postgresql_where=sa.text('is_active = true AND is_deleted = false'), sqlite_where=sa.text('is_active = true AND is_deleted = false'))
    op.create_unique_constraint('uq_template_version', 'template_versions', ['template_id', 'version_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_template_version', 'template_versions', type_='unique')
    op.drop_index('idx_active_template_version', table_name='template_versions', postgresql_where=sa.text('is_active = true AND is_deleted = false'), sqlite_where=sa.text('is_active = true AND is_deleted = false'))
    op.drop_column('template_versions', 'deleted_by')
    op.drop_column('template_versions', 'deleted_at')
    op.drop_column('template_versions', 'is_deleted')
    op.drop_column('template_versions', 'restored_from_version')
    op.drop_column('template_versions', 'template_is_active')
    op.drop_column('template_versions', 'variables')
    op.drop_column('template_versions', 'agent_type')
    op.drop_column('template_versions', 'format')
    op.drop_column('template_versions', 'locale')
    op.drop_column('template_versions', 'channel')
    op.drop_column('template_versions', 'type')
    op.drop_column('template_versions', 'name')
    op.drop_constraint(None, 'notification_templates', type_='foreignkey')
    op.drop_constraint('uq_notification_templates_lookup', 'notification_templates', type_='unique')
    op.drop_index(op.f('ix_notification_templates_tenant_id'), table_name='notification_templates')
    op.drop_index(op.f('ix_notification_templates_is_deleted'), table_name='notification_templates')
    op.drop_index(op.f('ix_notification_templates_agent_type'), table_name='notification_templates')
    op.drop_index('idx_managed_prompt_lookup', table_name='notification_templates')
    op.alter_column('notification_templates', 'deleted_by',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('notification_templates', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('notification_templates', 'agent_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'CommsAgent'::character varying"))
    op.alter_column('notification_templates', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'tenant-1'::character varying"))
    op.alter_column('notification_templates', 'variables',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.create_index(op.f('idx_dispatcher_notifications_tech_id'), 'dispatcher_notifications', ['tech_id'], unique=False)
    op.create_index(op.f('idx_audit_events_tech_id'), 'audit_events', ['tech_id'], unique=False)
    op.create_index(op.f('idx_assignment_overrides_job_id'), 'assignment_overrides', ['job_id'], unique=False)
    op.alter_column('agent_state_records', 'safe_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Safe operational metadata â€” no customer data or secrets.',
               existing_comment='Safe operational metadata — no customer data or secrets.',
               existing_nullable=True)
    op.alter_column('agent_state_records', 'last_error',
               existing_type=sa.VARCHAR(length=500),
               comment='Safe error summary only â€” no stack traces or secrets.',
               existing_comment='Safe error summary only — no stack traces or secrets.',
               existing_nullable=True)
    # ### end Alembic commands ###
